In [1]:
import numpy as np

def split_sequence(sequence, sliding_window_width):
    X, y = [], []
    for i in range(len(sequence)):
        # 找到最后一次滑动所截取数据中最后一个元素的索引，
        # 如果这个索引超过原序列中元素的索引则不截取；
        end_element_index = i + sliding_window_width
        if end_element_index > len(sequence) - 1: # 序列中最后一个元素的索引
            break
        sequence_x, sequence_y = sequence[i:end_element_index], sequence[end_element_index] # 取最后一个元素作为预测值y
        X.append(sequence_x)
        y.append(sequence_y)
    
    #return X,y
    return np.array(X), np.array(y)

if __name__ == '__main__':
    seq_test = [1,2,3,4,5,6,7,8,9,10]
    sw_width = 3
    seq_test_x, seq_test_y = split_sequence(seq_test, sw_width)
    print(seq_test_x.shape,seq_test_y.shape)
    for i in zip(seq_test_x,seq_test_y):
        print(i)
    for i in range(len(seq_test_x)):
        print(seq_test_x[i], seq_test_y[i])

(7, 3) (7,)
(array([1, 2, 3]), 4)
(array([2, 3, 4]), 5)
(array([3, 4, 5]), 6)
(array([4, 5, 6]), 7)
(array([5, 6, 7]), 8)
(array([6, 7, 8]), 9)
(array([7, 8, 9]), 10)
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
model = Sequential()
model.add(LSTM(32))
model.add(Dense(1))

In [4]:
seq_test_x_1 = seq_test_x.reshape((7,3,1))

In [5]:
seq_test_x_1

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [6]:
seq_test_x.shape[0]

7

In [7]:
seq_test_x.shape[1]

3

In [8]:
seq_test_x_2 = seq_test_x.reshape((seq_test_x.shape[0], seq_test_x.shape[1], 1))
seq_test_x_2

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]],

       [[5],
        [6],
        [7]],

       [[6],
        [7],
        [8]],

       [[7],
        [8],
        [9]]])

In [10]:
import numpy as np

simul_data = []
n = 5000
for i in range(n):
    simul_data.append([i+1, (i+1)*10]) # 第一列是时间列，第二列是特征数据列

simul_data = np.array(simul_data)
print(simul_data[:5, :]) # 取前5组数据
print(simul_data.shape)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
(5000, 2)


In [15]:
# 删除时间列
#simul_data = simul_data[:, 1]
simul_data.shape

(5000,)

In [18]:
samples = []
sw_steps = 200 # 滑动窗口步长

for i in range(0, n, sw_steps):
    sample = simul_data[i:i+sw_steps] # 截取 i 到 i + 200 的数据
    samples.append(sample)
print(len(samples))

25


In [22]:
simul_data = np.array(samples)
print(simul_data,simul_data.shape)

[[   10    20    30 ...  1980  1990  2000]
 [ 2010  2020  2030 ...  3980  3990  4000]
 [ 4010  4020  4030 ...  5980  5990  6000]
 ...
 [44010 44020 44030 ... 45980 45990 46000]
 [46010 46020 46030 ... 47980 47990 48000]
 [48010 48020 48030 ... 49980 49990 50000]] (25, 200)


In [21]:
simul_data.shape

(25, 200)

In [24]:
simul_data = simul_data.reshape((len(samples), sw_steps, 1))
print(simul_data.shape)

(25, 200, 1)
